### ISSUE TITLE
App version 0.2.0 not working on some smartphones.

### ISSUE THREAD

**Issue by Limon93** [openthermalcamera/Android-Application#3]
Hi Martin,
I successfully assembled your camera, thanks for the help you gave me last time.
As soon i finished the assembly i tried it with my phone usinge the app version 0.1.1 and it worked.
Later i tried the updated app 0.2.0 you released and i was not lucky. After some digging i found the problem.
But first let me explain the tests i made to discover it.
The first thing i tried was switching phones, i tried an Oneplus 5 a Pocophone F1 and a Xiaomi Mi6 all with android 9, no luck with all of these using your compiled app 0.2.0.
Then i tried the app 0.1.1 i compiled myself (compiled some time ago when i started building this project) and worked on all of my devices.
So i searched your commits and found [this one](https://github.com/openthermalcamera/Android-Application/commit/d98898961c3399417b663bfc603048e4134c8d42)interesting.
In the file "UsbService.java" i noticed that you changed the vid/pid check system. 
Simply i reverted the changes and recompiled the app 0.2.0 ( I readded line 26-27 and removed the new added lines 29-30 and 170 to 188). Now it is working on all my devices. 
Do you have a working phone with your 0.2.0 app?

I have a suggestion too. I noticed you used bilinear interpolation to smooth the image on android thanks to an system function, but i think a bicubic interpolation would be way better. I have an open source working snippet of code written in C that transforms a matrix[X][X] to a bigger matrix [Y][Y] using bicubic interpolation. I will give it to you if you find it useful.

Thanks for your time.

Regards,
Simone.

**Comment by themarpe** [comment]
Hi Simone!

That sounds fantastic! I hope you like it :)
Regarding the problem, it's because I've changed the VID/PID pair in between to an unique pair from pid codes project.
Please reflash the STM microcontroller to latest firmware version (Available as release in firmware repository), and try again with unmodified 0.2.0 Android version. (Side note: the Android application is also available in Google Play Store :) )
I'd love to give it a try. I was also notified of the following gaussian based interpolation: http://blog.dzl.dk/2019/06/08/compact-gaussian-interpolation-for-small-displays/
How does this one relate to your technique?
If one is better I'll implement that one.

Best regards,
Martin

**Comment by Limon93** [comment]
Hi Martin!
Sorry for the late response,
I updated the firmare of the camera and everything worked! 
Thank you again for your time.
Regarding the bicubic interpolation there is a sketch from [this adafruit repository](https://github.com/adafruit/Adafruit_AMG88xx/tree/master/examples/thermal_cam_interpolate) containing the snippet i was talking about.
Choosing between gaussian and bicubic is difficult in your case, i made two examples [here](https://drive.google.com/file/d/1NCOvw2_nOG7Mv-GhICXBnaPVO2u4krz8/view?usp=sharing) to better understand the graphical effect of the two interpolation methods.

Best regards,
Simone.

**Comment by themarpe** [comment]
Hi Simone!
That's great to hear!

Thanks for the examples. I think the gaussian looks a bit better than bicubic. When I find the time, I'll give it a go and implement it.

Best regards, 
Martin
